// HSK 1-2 Vocabulary Dataset (~300 entries)
const VOCABULARY = [
  // === HSK 1 ===

  // Pronouns
  { id: 1, chinese: "我", pinyin: "wǒ", english: "I / me", hsk: 1, category: "pronouns" },
  { id: 2, chinese: "你", pinyin: "nǐ", english: "you", hsk: 1, category: "pronouns" },
  { id: 3, chinese: "他", pinyin: "tā", english: "he / him", hsk: 1, category: "pronouns" },
  { id: 4, chinese: "她", pinyin: "tā", english: "she / her", hsk: 1, category: "pronouns" },
  { id: 5, chinese: "我们", pinyin: "wǒmen", english: "we / us", hsk: 1, category: "pronouns" },
  { id: 6, chinese: "他们", pinyin: "tāmen", english: "they / them", hsk: 1, category: "pronouns" },
  { id: 7, chinese: "这", pinyin: "zhè", english: "this", hsk: 1, category: "pronouns" },
  { id: 8, chinese: "那", pinyin: "nà", english: "that", hsk: 1, category: "pronouns" },
  { id: 9, chinese: "哪", pinyin: "nǎ", english: "which", hsk: 1, category: "pronouns" },
  { id: 10, chinese: "谁", pinyin: "shéi", english: "who", hsk: 1, category: "pronouns" },
  { id: 11, chinese: "什么", pinyin: "shénme", english: "what", hsk: 1, category: "pronouns" },
  { id: 12, chinese: "多少", pinyin: "duōshao", english: "how many / how much", hsk: 1, category: "pronouns" },
  { id: 13, chinese: "几", pinyin: "jǐ", english: "how many (small number)", hsk: 1, category: "pronouns" },
  { id: 14, chinese: "怎么", pinyin: "zěnme", english: "how", hsk: 1, category: "pronouns" },
  { id: 15, chinese: "怎么样", pinyin: "zěnmeyàng", english: "how about", hsk: 1, category: "pronouns" },

  // Greetings
  { id: 16, chinese: "你好", pinyin: "nǐ hǎo", english: "hello", hsk: 1, category: "greetings" },
  { id: 17, chinese: "谢谢", pinyin: "xièxie", english: "thank you", hsk: 1, category: "greetings" },
  { id: 18, chinese: "不客气", pinyin: "bú kèqi", english: "you're welcome", hsk: 1, category: "greetings" },
  { id: 19, chinese: "对不起", pinyin: "duìbuqǐ", english: "sorry", hsk: 1, category: "greetings" },
  { id: 20, chinese: "没关系", pinyin: "méi guānxi", english: "it doesn't matter", hsk: 1, category: "greetings" },
  { id: 21, chinese: "再见", pinyin: "zàijiàn", english: "goodbye", hsk: 1, category: "greetings" },
  { id: 22, chinese: "请", pinyin: "qǐng", english: "please", hsk: 1, category: "greetings" },

  // Numbers
  { id: 23, chinese: "一", pinyin: "yī", english: "one", hsk: 1, category: "numbers" },
  { id: 24, chinese: "二", pinyin: "èr", english: "two", hsk: 1, category: "numbers" },
  { id: 25, chinese: "三", pinyin: "sān", english: "three", hsk: 1, category: "numbers" },
  { id: 26, chinese: "四", pinyin: "sì", english: "four", hsk: 1, category: "numbers" },
  { id: 27, chinese: "五", pinyin: "wǔ", english: "five", hsk: 1, category: "numbers" },
  { id: 28, chinese: "六", pinyin: "liù", english: "six", hsk: 1, category: "numbers" },
  { id: 29, chinese: "七", pinyin: "qī", english: "seven", hsk: 1, category: "numbers" },
  { id: 30, chinese: "八", pinyin: "bā", english: "eight", hsk: 1, category: "numbers" },
  { id: 31, chinese: "九", pinyin: "jiǔ", english: "nine", hsk: 1, category: "numbers" },
  { id: 32, chinese: "十", pinyin: "shí", english: "ten", hsk: 1, category: "numbers" },
  { id: 33, chinese: "零", pinyin: "líng", english: "zero", hsk: 1, category: "numbers" },
  { id: 34, chinese: "百", pinyin: "bǎi", english: "hundred", hsk: 1, category: "numbers" },
  { id: 35, chinese: "千", pinyin: "qiān", english: "thousand", hsk: 1, category: "numbers" },
  { id: 36, chinese: "两", pinyin: "liǎng", english: "two (measure)", hsk: 1, category: "numbers" },

  // Time
  { id: 37, chinese: "今天", pinyin: "jīntiān", english: "today", hsk: 1, category: "time" },
  { id: 38, chinese: "明天", pinyin: "míngtiān", english: "tomorrow", hsk: 1, category: "time" },
  { id: 39, chinese: "昨天", pinyin: "zuótiān", english: "yesterday", hsk: 1, category: "time" },
  { id: 40, chinese: "现在", pinyin: "xiànzài", english: "now", hsk: 1, category: "time" },
  { id: 41, chinese: "时候", pinyin: "shíhou", english: "time / moment", hsk: 1, category: "time" },
  { id: 42, chinese: "年", pinyin: "nián", english: "year", hsk: 1, category: "time" },
  { id: 43, chinese: "月", pinyin: "yuè", english: "month", hsk: 1, category: "time" },
  { id: 44, chinese: "日", pinyin: "rì", english: "day / date", hsk: 1, category: "time" },
  { id: 45, chinese: "星期", pinyin: "xīngqī", english: "week", hsk: 1, category: "time" },
  { id: 46, chinese: "点", pinyin: "diǎn", english: "o'clock", hsk: 1, category: "time" },
  { id: 47, chinese: "分钟", pinyin: "fēnzhōng", english: "minute", hsk: 1, category: "time" },
  { id: 48, chinese: "上午", pinyin: "shàngwǔ", english: "morning (AM)", hsk: 1, category: "time" },
  { id: 49, chinese: "下午", pinyin: "xiàwǔ", english: "afternoon (PM)", hsk: 1, category: "time" },

  // Family
  { id: 50, chinese: "爸爸", pinyin: "bàba", english: "father", hsk: 1, category: "family" },
  { id: 51, chinese: "妈妈", pinyin: "māma", english: "mother", hsk: 1, category: "family" },
  { id: 52, chinese: "儿子", pinyin: "érzi", english: "son", hsk: 1, category: "family" },
  { id: 53, chinese: "女儿", pinyin: "nǚ'ér", english: "daughter", hsk: 1, category: "family" },
  { id: 54, chinese: "家", pinyin: "jiā", english: "home / family", hsk: 1, category: "family" },
  { id: 55, chinese: "人", pinyin: "rén", english: "person / people", hsk: 1, category: "family" },
  { id: 56, chinese: "朋友", pinyin: "péngyou", english: "friend", hsk: 1, category: "family" },
  { id: 57, chinese: "先生", pinyin: "xiānsheng", english: "Mr. / sir", hsk: 1, category: "family" },
  { id: 58, chinese: "小姐", pinyin: "xiǎojiě", english: "Miss / young lady", hsk: 1, category: "family" },
  { id: 59, chinese: "同学", pinyin: "tóngxué", english: "classmate", hsk: 1, category: "family" },
  { id: 60, chinese: "老师", pinyin: "lǎoshī", english: "teacher", hsk: 1, category: "family" },

  // Food & Drink
  { id: 61, chinese: "水", pinyin: "shuǐ", english: "water", hsk: 1, category: "food" },
  { id: 62, chinese: "茶", pinyin: "chá", english: "tea", hsk: 1, category: "food" },
  { id: 63, chinese: "米饭", pinyin: "mǐfàn", english: "rice", hsk: 1, category: "food" },
  { id: 64, chinese: "菜", pinyin: "cài", english: "dish / vegetable", hsk: 1, category: "food" },
  { id: 65, chinese: "苹果", pinyin: "píngguǒ", english: "apple", hsk: 1, category: "food" },
  { id: 66, chinese: "杯子", pinyin: "bēizi", english: "cup / glass", hsk: 1, category: "food" },
  { id: 67, chinese: "饭店", pinyin: "fàndiàn", english: "restaurant", hsk: 1, category: "food" },
  { id: 68, chinese: "吃", pinyin: "chī", english: "to eat", hsk: 1, category: "food" },
  { id: 69, chinese: "喝", pinyin: "hē", english: "to drink", hsk: 1, category: "food" },

  // Common Verbs
  { id: 70, chinese: "是", pinyin: "shì", english: "to be", hsk: 1, category: "verbs" },
  { id: 71, chinese: "有", pinyin: "yǒu", english: "to have", hsk: 1, category: "verbs" },
  { id: 72, chinese: "看", pinyin: "kàn", english: "to see / to look", hsk: 1, category: "verbs" },
  { id: 73, chinese: "听", pinyin: "tīng", english: "to listen", hsk: 1, category: "verbs" },
  { id: 74, chinese: "说", pinyin: "shuō", english: "to speak / to say", hsk: 1, category: "verbs" },
  { id: 75, chinese: "读", pinyin: "dú", english: "to read", hsk: 1, category: "verbs" },
  { id: 76, chinese: "写", pinyin: "xiě", english: "to write", hsk: 1, category: "verbs" },
  { id: 77, chinese: "去", pinyin: "qù", english: "to go", hsk: 1, category: "verbs" },
  { id: 78, chinese: "来", pinyin: "lái", english: "to come", hsk: 1, category: "verbs" },
  { id: 79, chinese: "回", pinyin: "huí", english: "to return", hsk: 1, category: "verbs" },
  { id: 80, chinese: "做", pinyin: "zuò", english: "to do / to make", hsk: 1, category: "verbs" },
  { id: 81, chinese: "想", pinyin: "xiǎng", english: "to want / to think", hsk: 1, category: "verbs" },
  { id: 82, chinese: "会", pinyin: "huì", english: "can / will", hsk: 1, category: "verbs" },
  { id: 83, chinese: "能", pinyin: "néng", english: "can / able to", hsk: 1, category: "verbs" },
  { id: 84, chinese: "叫", pinyin: "jiào", english: "to be called", hsk: 1, category: "verbs" },
  { id: 85, chinese: "爱", pinyin: "ài", english: "to love", hsk: 1, category: "verbs" },
  { id: 86, chinese: "喜欢", pinyin: "xǐhuan", english: "to like", hsk: 1, category: "verbs" },
  { id: 87, chinese: "知道", pinyin: "zhīdào", english: "to know", hsk: 1, category: "verbs" },
  { id: 88, chinese: "认识", pinyin: "rènshi", english: "to recognize / to know (a person)", hsk: 1, category: "verbs" },
  { id: 89, chinese: "学习", pinyin: "xuéxí", english: "to study", hsk: 1, category: "verbs" },
  { id: 90, chinese: "工作", pinyin: "gōngzuò", english: "to work / work", hsk: 1, category: "verbs" },
  { id: 91, chinese: "住", pinyin: "zhù", english: "to live / to stay", hsk: 1, category: "verbs" },
  { id: 92, chinese: "坐", pinyin: "zuò", english: "to sit", hsk: 1, category: "verbs" },
  { id: 93, chinese: "买", pinyin: "mǎi", english: "to buy", hsk: 1, category: "verbs" },
  { id: 94, chinese: "开", pinyin: "kāi", english: "to open / to drive", hsk: 1, category: "verbs" },
  { id: 95, chinese: "打电话", pinyin: "dǎ diànhuà", english: "to make a phone call", hsk: 1, category: "verbs" },
  { id: 96, chinese: "睡觉", pinyin: "shuìjiào", english: "to sleep", hsk: 1, category: "verbs" },

  // Adjectives
  { id: 97, chinese: "好", pinyin: "hǎo", english: "good", hsk: 1, category: "adjectives" },
  { id: 98, chinese: "大", pinyin: "dà", english: "big", hsk: 1, category: "adjectives" },
  { id: 99, chinese: "小", pinyin: "xiǎo", english: "small", hsk: 1, category: "adjectives" },
  { id: 100, chinese: "多", pinyin: "duō", english: "many / much", hsk: 1, category: "adjectives" },
  { id: 101, chinese: "少", pinyin: "shǎo", english: "few / little", hsk: 1, category: "adjectives" },
  { id: 102, chinese: "冷", pinyin: "lěng", english: "cold", hsk: 1, category: "adjectives" },
  { id: 103, chinese: "热", pinyin: "rè", english: "hot", hsk: 1, category: "adjectives" },
  { id: 104, chinese: "高兴", pinyin: "gāoxìng", english: "happy", hsk: 1, category: "adjectives" },
  { id: 105, chinese: "漂亮", pinyin: "piàoliang", english: "pretty / beautiful", hsk: 1, category: "adjectives" },

  // Places
  { id: 106, chinese: "中国", pinyin: "Zhōngguó", english: "China", hsk: 1, category: "places" },
  { id: 107, chinese: "北京", pinyin: "Běijīng", english: "Beijing", hsk: 1, category: "places" },
  { id: 108, chinese: "学校", pinyin: "xuéxiào", english: "school", hsk: 1, category: "places" },
  { id: 109, chinese: "医院", pinyin: "yīyuàn", english: "hospital", hsk: 1, category: "places" },
  { id: 110, chinese: "商店", pinyin: "shāngdiàn", english: "shop / store", hsk: 1, category: "places" },
  { id: 111, chinese: "前面", pinyin: "qiánmiàn", english: "in front of", hsk: 1, category: "places" },
  { id: 112, chinese: "后面", pinyin: "hòumiàn", english: "behind", hsk: 1, category: "places" },
  { id: 113, chinese: "里", pinyin: "lǐ", english: "inside", hsk: 1, category: "places" },
  { id: 114, chinese: "上", pinyin: "shàng", english: "above / on", hsk: 1, category: "places" },
  { id: 115, chinese: "下", pinyin: "xià", english: "below / under", hsk: 1, category: "places" },

  // Objects
  { id: 116, chinese: "书", pinyin: "shū", english: "book", hsk: 1, category: "objects" },
  { id: 117, chinese: "电脑", pinyin: "diànnǎo", english: "computer", hsk: 1, category: "objects" },
  { id: 118, chinese: "电视", pinyin: "diànshì", english: "television", hsk: 1, category: "objects" },
  { id: 119, chinese: "电影", pinyin: "diànyǐng", english: "movie", hsk: 1, category: "objects" },
  { id: 120, chinese: "钱", pinyin: "qián", english: "money", hsk: 1, category: "objects" },
  { id: 121, chinese: "桌子", pinyin: "zhuōzi", english: "table", hsk: 1, category: "objects" },
  { id: 122, chinese: "椅子", pinyin: "yǐzi", english: "chair", hsk: 1, category: "objects" },
  { id: 123, chinese: "衣服", pinyin: "yīfu", english: "clothes", hsk: 1, category: "objects" },
  { id: 124, chinese: "车", pinyin: "chē", english: "car / vehicle", hsk: 1, category: "objects" },
  { id: 125, chinese: "飞机", pinyin: "fēijī", english: "airplane", hsk: 1, category: "objects" },
  { id: 126, chinese: "猫", pinyin: "māo", english: "cat", hsk: 1, category: "objects" },
  { id: 127, chinese: "狗", pinyin: "gǒu", english: "dog", hsk: 1, category: "objects" },

  // Weather & Nature
  { id: 128, chinese: "天气", pinyin: "tiānqì", english: "weather", hsk: 1, category: "weather" },
  { id: 129, chinese: "下雨", pinyin: "xià yǔ", english: "to rain", hsk: 1, category: "weather" },

  // Particles & Grammar
  { id: 130, chinese: "的", pinyin: "de", english: "possessive particle", hsk: 1, category: "particles" },
  { id: 131, chinese: "了", pinyin: "le", english: "completed action particle", hsk: 1, category: "particles" },
  { id: 132, chinese: "吗", pinyin: "ma", english: "question particle", hsk: 1, category: "particles" },
  { id: 133, chinese: "不", pinyin: "bù", english: "not / no", hsk: 1, category: "particles" },
  { id: 134, chinese: "没", pinyin: "méi", english: "not (have)", hsk: 1, category: "particles" },
  { id: 135, chinese: "很", pinyin: "hěn", english: "very", hsk: 1, category: "particles" },
  { id: 136, chinese: "都", pinyin: "dōu", english: "all / both", hsk: 1, category: "particles" },
  { id: 137, chinese: "在", pinyin: "zài", english: "at / in", hsk: 1, category: "particles" },
  { id: 138, chinese: "和", pinyin: "hé", english: "and", hsk: 1, category: "particles" },
  { id: 139, chinese: "太", pinyin: "tài", english: "too (excessive)", hsk: 1, category: "particles" },
  { id: 140, chinese: "个", pinyin: "gè", english: "general measure word", hsk: 1, category: "particles" },
  { id: 141, chinese: "岁", pinyin: "suì", english: "years old", hsk: 1, category: "particles" },
  { id: 142, chinese: "块", pinyin: "kuài", english: "measure word for money", hsk: 1, category: "particles" },
  { id: 143, chinese: "些", pinyin: "xiē", english: "some", hsk: 1, category: "particles" },
  { id: 144, chinese: "本", pinyin: "běn", english: "measure word for books", hsk: 1, category: "particles" },

  // Body & Health
  { id: 145, chinese: "医生", pinyin: "yīshēng", english: "doctor", hsk: 1, category: "body" },
  { id: 146, chinese: "名字", pinyin: "míngzi", english: "name", hsk: 1, category: "body" },
  { id: 147, chinese: "汉语", pinyin: "Hànyǔ", english: "Chinese language", hsk: 1, category: "body" },
  { id: 148, chinese: "字", pinyin: "zì", english: "character / word", hsk: 1, category: "body" },
  { id: 149, chinese: "东西", pinyin: "dōngxi", english: "thing / stuff", hsk: 1, category: "objects" },
  { id: 150, chinese: "岁", pinyin: "suì", english: "age / years old", hsk: 1, category: "body" },

  // === HSK 2 ===

  // Pronouns & Question Words (HSK 2)
  { id: 151, chinese: "每", pinyin: "měi", english: "every / each", hsk: 2, category: "pronouns" },
  { id: 152, chinese: "为什么", pinyin: "wèishénme", english: "why", hsk: 2, category: "pronouns" },
  { id: 153, chinese: "自己", pinyin: "zìjǐ", english: "oneself", hsk: 2, category: "pronouns" },
  { id: 154, chinese: "它", pinyin: "tā", english: "it", hsk: 2, category: "pronouns" },
  { id: 155, chinese: "大家", pinyin: "dàjiā", english: "everyone", hsk: 2, category: "pronouns" },

  // Time (HSK 2)
  { id: 156, chinese: "早上", pinyin: "zǎoshang", english: "morning", hsk: 2, category: "time" },
  { id: 157, chinese: "晚上", pinyin: "wǎnshang", english: "evening / night", hsk: 2, category: "time" },
  { id: 158, chinese: "小时", pinyin: "xiǎoshí", english: "hour", hsk: 2, category: "time" },
  { id: 159, chinese: "去年", pinyin: "qùnián", english: "last year", hsk: 2, category: "time" },
  { id: 160, chinese: "已经", pinyin: "yǐjīng", english: "already", hsk: 2, category: "time" },
  { id: 161, chinese: "刚才", pinyin: "gāngcái", english: "just now", hsk: 2, category: "time" },
  { id: 162, chinese: "以前", pinyin: "yǐqián", english: "before / previously", hsk: 2, category: "time" },
  { id: 163, chinese: "以后", pinyin: "yǐhòu", english: "after / later", hsk: 2, category: "time" },
  { id: 164, chinese: "第一", pinyin: "dì yī", english: "first", hsk: 2, category: "time" },

  // Family & People (HSK 2)
  { id: 165, chinese: "哥哥", pinyin: "gēge", english: "older brother", hsk: 2, category: "family" },
  { id: 166, chinese: "姐姐", pinyin: "jiějie", english: "older sister", hsk: 2, category: "family" },
  { id: 167, chinese: "弟弟", pinyin: "dìdi", english: "younger brother", hsk: 2, category: "family" },
  { id: 168, chinese: "妹妹", pinyin: "mèimei", english: "younger sister", hsk: 2, category: "family" },
  { id: 169, chinese: "丈夫", pinyin: "zhàngfu", english: "husband", hsk: 2, category: "family" },
  { id: 170, chinese: "妻子", pinyin: "qīzi", english: "wife", hsk: 2, category: "family" },
  { id: 171, chinese: "孩子", pinyin: "háizi", english: "child / children", hsk: 2, category: "family" },
  { id: 172, chinese: "男人", pinyin: "nánrén", english: "man", hsk: 2, category: "family" },
  { id: 173, chinese: "女人", pinyin: "nǚrén", english: "woman", hsk: 2, category: "family" },

  // Food & Drink (HSK 2)
  { id: 174, chinese: "鸡蛋", pinyin: "jīdàn", english: "egg", hsk: 2, category: "food" },
  { id: 175, chinese: "牛奶", pinyin: "niúnǎi", english: "milk", hsk: 2, category: "food" },
  { id: 176, chinese: "鱼", pinyin: "yú", english: "fish", hsk: 2, category: "food" },
  { id: 177, chinese: "羊肉", pinyin: "yángròu", english: "lamb / mutton", hsk: 2, category: "food" },
  { id: 178, chinese: "西瓜", pinyin: "xīguā", english: "watermelon", hsk: 2, category: "food" },
  { id: 179, chinese: "咖啡", pinyin: "kāfēi", english: "coffee", hsk: 2, category: "food" },
  { id: 180, chinese: "面条", pinyin: "miàntiáo", english: "noodles", hsk: 2, category: "food" },

  // Verbs (HSK 2)
  { id: 181, chinese: "帮助", pinyin: "bāngzhù", english: "to help", hsk: 2, category: "verbs" },
  { id: 182, chinese: "准备", pinyin: "zhǔnbèi", english: "to prepare", hsk: 2, category: "verbs" },
  { id: 183, chinese: "开始", pinyin: "kāishǐ", english: "to begin / to start", hsk: 2, category: "verbs" },
  { id: 184, chinese: "完", pinyin: "wán", english: "to finish", hsk: 2, category: "verbs" },
  { id: 185, chinese: "觉得", pinyin: "juéde", english: "to think / to feel", hsk: 2, category: "verbs" },
  { id: 186, chinese: "希望", pinyin: "xīwàng", english: "to hope / to wish", hsk: 2, category: "verbs" },
  { id: 187, chinese: "告诉", pinyin: "gàosu", english: "to tell", hsk: 2, category: "verbs" },
  { id: 188, chinese: "问", pinyin: "wèn", english: "to ask", hsk: 2, category: "verbs" },
  { id: 189, chinese: "回答", pinyin: "huídá", english: "to answer", hsk: 2, category: "verbs" },
  { id: 190, chinese: "找", pinyin: "zhǎo", english: "to find / to look for", hsk: 2, category: "verbs" },
  { id: 191, chinese: "给", pinyin: "gěi", english: "to give", hsk: 2, category: "verbs" },
  { id: 192, chinese: "到", pinyin: "dào", english: "to arrive", hsk: 2, category: "verbs" },
  { id: 193, chinese: "走", pinyin: "zǒu", english: "to walk", hsk: 2, category: "verbs" },
  { id: 194, chinese: "跑步", pinyin: "pǎobù", english: "to run / jogging", hsk: 2, category: "verbs" },
  { id: 195, chinese: "游泳", pinyin: "yóuyǒng", english: "to swim", hsk: 2, category: "verbs" },
  { id: 196, chinese: "踢足球", pinyin: "tī zúqiú", english: "to play football", hsk: 2, category: "verbs" },
  { id: 197, chinese: "打篮球", pinyin: "dǎ lánqiú", english: "to play basketball", hsk: 2, category: "verbs" },
  { id: 198, chinese: "唱歌", pinyin: "chànggē", english: "to sing", hsk: 2, category: "verbs" },
  { id: 199, chinese: "跳舞", pinyin: "tiàowǔ", english: "to dance", hsk: 2, category: "verbs" },
  { id: 200, chinese: "旅游", pinyin: "lǚyóu", english: "to travel", hsk: 2, category: "verbs" },
  { id: 201, chinese: "上班", pinyin: "shàngbān", english: "to go to work", hsk: 2, category: "verbs" },
  { id: 202, chinese: "生病", pinyin: "shēngbìng", english: "to get sick", hsk: 2, category: "verbs" },
  { id: 203, chinese: "休息", pinyin: "xiūxi", english: "to rest", hsk: 2, category: "verbs" },
  { id: 204, chinese: "起床", pinyin: "qǐchuáng", english: "to get up", hsk: 2, category: "verbs" },
  { id: 205, chinese: "送", pinyin: "sòng", english: "to give (a gift) / to send", hsk: 2, category: "verbs" },
  { id: 206, chinese: "卖", pinyin: "mài", english: "to sell", hsk: 2, category: "verbs" },
  { id: 207, chinese: "等", pinyin: "děng", english: "to wait", hsk: 2, category: "verbs" },
  { id: 208, chinese: "让", pinyin: "ràng", english: "to let / to allow", hsk: 2, category: "verbs" },
  { id: 209, chinese: "进", pinyin: "jìn", english: "to enter", hsk: 2, category: "verbs" },
  { id: 210, chinese: "出", pinyin: "chū", english: "to go out", hsk: 2, category: "verbs" },
  { id: 211, chinese: "穿", pinyin: "chuān", english: "to wear", hsk: 2, category: "verbs" },
  { id: 212, chinese: "玩", pinyin: "wán", english: "to play / to have fun", hsk: 2, category: "verbs" },
  { id: 213, chinese: "笑", pinyin: "xiào", english: "to laugh / to smile", hsk: 2, category: "verbs" },
  { id: 214, chinese: "哭", pinyin: "kū", english: "to cry", hsk: 2, category: "verbs" },
  { id: 215, chinese: "懂", pinyin: "dǒng", english: "to understand", hsk: 2, category: "verbs" },
  { id: 216, chinese: "介绍", pinyin: "jièshào", english: "to introduce", hsk: 2, category: "verbs" },
  { id: 217, chinese: "考试", pinyin: "kǎoshì", english: "exam / to take a test", hsk: 2, category: "verbs" },

  // Adjectives (HSK 2)
  { id: 218, chinese: "快", pinyin: "kuài", english: "fast / quick", hsk: 2, category: "adjectives" },
  { id: 219, chinese: "慢", pinyin: "màn", english: "slow", hsk: 2, category: "adjectives" },
  { id: 220, chinese: "新", pinyin: "xīn", english: "new", hsk: 2, category: "adjectives" },
  { id: 221, chinese: "旧", pinyin: "jiù", english: "old (things)", hsk: 2, category: "adjectives" },
  { id: 222, chinese: "长", pinyin: "cháng", english: "long", hsk: 2, category: "adjectives" },
  { id: 223, chinese: "短", pinyin: "duǎn", english: "short (length)", hsk: 2, category: "adjectives" },
  { id: 224, chinese: "高", pinyin: "gāo", english: "tall / high", hsk: 2, category: "adjectives" },
  { id: 225, chinese: "矮", pinyin: "ǎi", english: "short (height)", hsk: 2, category: "adjectives" },
  { id: 226, chinese: "贵", pinyin: "guì", english: "expensive", hsk: 2, category: "adjectives" },
  { id: 227, chinese: "便宜", pinyin: "piányi", english: "cheap", hsk: 2, category: "adjectives" },
  { id: 228, chinese: "忙", pinyin: "máng", english: "busy", hsk: 2, category: "adjectives" },
  { id: 229, chinese: "累", pinyin: "lèi", english: "tired", hsk: 2, category: "adjectives" },
  { id: 230, chinese: "远", pinyin: "yuǎn", english: "far", hsk: 2, category: "adjectives" },
  { id: 231, chinese: "近", pinyin: "jìn", english: "near / close", hsk: 2, category: "adjectives" },
  { id: 232, chinese: "好吃", pinyin: "hǎochī", english: "delicious", hsk: 2, category: "adjectives" },
  { id: 233, chinese: "白", pinyin: "bái", english: "white", hsk: 2, category: "adjectives" },
  { id: 234, chinese: "黑", pinyin: "hēi", english: "black", hsk: 2, category: "adjectives" },
  { id: 235, chinese: "红", pinyin: "hóng", english: "red", hsk: 2, category: "adjectives" },
  { id: 236, chinese: "错", pinyin: "cuò", english: "wrong / incorrect", hsk: 2, category: "adjectives" },
  { id: 237, chinese: "对", pinyin: "duì", english: "correct / right", hsk: 2, category: "adjectives" },
  { id: 238, chinese: "快乐", pinyin: "kuàilè", english: "happy / joyful", hsk: 2, category: "adjectives" },
  { id: 239, chinese: "生气", pinyin: "shēngqì", english: "angry", hsk: 2, category: "adjectives" },
  { id: 240, chinese: "重要", pinyin: "zhòngyào", english: "important", hsk: 2, category: "adjectives" },

  // Places (HSK 2)
  { id: 241, chinese: "公司", pinyin: "gōngsī", english: "company", hsk: 2, category: "places" },
  { id: 242, chinese: "机场", pinyin: "jīchǎng", english: "airport", hsk: 2, category: "places" },
  { id: 243, chinese: "教室", pinyin: "jiàoshì", english: "classroom", hsk: 2, category: "places" },
  { id: 244, chinese: "房间", pinyin: "fángjiān", english: "room", hsk: 2, category: "places" },
  { id: 245, chinese: "路", pinyin: "lù", english: "road / path", hsk: 2, category: "places" },
  { id: 246, chinese: "旁边", pinyin: "pángbiān", english: "beside / next to", hsk: 2, category: "places" },
  { id: 247, chinese: "外", pinyin: "wài", english: "outside", hsk: 2, category: "places" },
  { id: 248, chinese: "左", pinyin: "zuǒ", english: "left", hsk: 2, category: "places" },
  { id: 249, chinese: "右", pinyin: "yòu", english: "right", hsk: 2, category: "places" },

  // Objects (HSK 2)
  { id: 250, chinese: "手机", pinyin: "shǒujī", english: "mobile phone", hsk: 2, category: "objects" },
  { id: 251, chinese: "手表", pinyin: "shǒubiǎo", english: "wristwatch", hsk: 2, category: "objects" },
  { id: 252, chinese: "眼睛", pinyin: "yǎnjing", english: "eye", hsk: 2, category: "objects" },
  { id: 253, chinese: "身体", pinyin: "shēntǐ", english: "body / health", hsk: 2, category: "objects" },
  { id: 254, chinese: "报纸", pinyin: "bàozhǐ", english: "newspaper", hsk: 2, category: "objects" },
  { id: 255, chinese: "门", pinyin: "mén", english: "door / gate", hsk: 2, category: "objects" },
  { id: 256, chinese: "题", pinyin: "tí", english: "question / problem", hsk: 2, category: "objects" },
  { id: 257, chinese: "课", pinyin: "kè", english: "class / lesson", hsk: 2, category: "objects" },
  { id: 258, chinese: "事情", pinyin: "shìqing", english: "matter / thing", hsk: 2, category: "objects" },
  { id: 259, chinese: "颜色", pinyin: "yánsè", english: "color", hsk: 2, category: "objects" },
  { id: 260, chinese: "药", pinyin: "yào", english: "medicine", hsk: 2, category: "objects" },
  { id: 261, chinese: "票", pinyin: "piào", english: "ticket", hsk: 2, category: "objects" },
  { id: 262, chinese: "铅笔", pinyin: "qiānbǐ", english: "pencil", hsk: 2, category: "objects" },

  // Transport (HSK 2)
  { id: 263, chinese: "公共汽车", pinyin: "gōnggòng qìchē", english: "bus", hsk: 2, category: "transport" },
  { id: 264, chinese: "出租车", pinyin: "chūzūchē", english: "taxi", hsk: 2, category: "transport" },
  { id: 265, chinese: "火车站", pinyin: "huǒchēzhàn", english: "train station", hsk: 2, category: "transport" },
  { id: 266, chinese: "自行车", pinyin: "zìxíngchē", english: "bicycle", hsk: 2, category: "transport" },
  { id: 267, chinese: "船", pinyin: "chuán", english: "boat / ship", hsk: 2, category: "transport" },

  // Weather (HSK 2)
  { id: 268, chinese: "晴天", pinyin: "qíngtiān", english: "sunny day", hsk: 2, category: "weather" },
  { id: 269, chinese: "阴天", pinyin: "yīntiān", english: "cloudy day", hsk: 2, category: "weather" },
  { id: 270, chinese: "下雪", pinyin: "xià xuě", english: "to snow", hsk: 2, category: "weather" },
  { id: 271, chinese: "刮风", pinyin: "guā fēng", english: "to blow (wind)", hsk: 2, category: "weather" },

  // Particles & Grammar (HSK 2)
  { id: 272, chinese: "还", pinyin: "hái", english: "still / also", hsk: 2, category: "particles" },
  { id: 273, chinese: "再", pinyin: "zài", english: "again", hsk: 2, category: "particles" },
  { id: 274, chinese: "就", pinyin: "jiù", english: "then / just", hsk: 2, category: "particles" },
  { id: 275, chinese: "才", pinyin: "cái", english: "only then / just", hsk: 2, category: "particles" },
  { id: 276, chinese: "别", pinyin: "bié", english: "don't", hsk: 2, category: "particles" },
  { id: 277, chinese: "最", pinyin: "zuì", english: "most", hsk: 2, category: "particles" },
  { id: 278, chinese: "真", pinyin: "zhēn", english: "really / truly", hsk: 2, category: "particles" },
  { id: 279, chinese: "非常", pinyin: "fēicháng", english: "very / extremely", hsk: 2, category: "particles" },
  { id: 280, chinese: "可能", pinyin: "kěnéng", english: "possibly / maybe", hsk: 2, category: "particles" },
  { id: 281, chinese: "可以", pinyin: "kěyǐ", english: "may / can", hsk: 2, category: "particles" },
  { id: 282, chinese: "因为", pinyin: "yīnwèi", english: "because", hsk: 2, category: "particles" },
  { id: 283, chinese: "所以", pinyin: "suǒyǐ", english: "therefore", hsk: 2, category: "particles" },
  { id: 284, chinese: "但是", pinyin: "dànshì", english: "but / however", hsk: 2, category: "particles" },
  { id: 285, chinese: "虽然", pinyin: "suīrán", english: "although", hsk: 2, category: "particles" },
  { id: 286, chinese: "如果", pinyin: "rúguǒ", english: "if", hsk: 2, category: "particles" },
  { id: 287, chinese: "从", pinyin: "cóng", english: "from", hsk: 2, category: "particles" },
  { id: 288, chinese: "向", pinyin: "xiàng", english: "toward", hsk: 2, category: "particles" },
  { id: 289, chinese: "离", pinyin: "lí", english: "from (distance)", hsk: 2, category: "particles" },
  { id: 290, chinese: "比", pinyin: "bǐ", english: "compared to", hsk: 2, category: "particles" },
  { id: 291, chinese: "更", pinyin: "gèng", english: "even more", hsk: 2, category: "particles" },
  { id: 292, chinese: "着", pinyin: "zhe", english: "ongoing action particle", hsk: 2, category: "particles" },
  { id: 293, chinese: "过", pinyin: "guò", english: "experienced action particle", hsk: 2, category: "particles" },
  { id: 294, chinese: "得", pinyin: "de", english: "complement particle", hsk: 2, category: "particles" },
  { id: 295, chinese: "把", pinyin: "bǎ", english: "object marker particle", hsk: 2, category: "particles" },
  { id: 296, chinese: "被", pinyin: "bèi", english: "passive marker", hsk: 2, category: "particles" },

  // Body & Health (HSK 2)
  { id: 297, chinese: "头", pinyin: "tóu", english: "head", hsk: 2, category: "body" },
  { id: 298, chinese: "脸", pinyin: "liǎn", english: "face", hsk: 2, category: "body" },
  { id: 299, chinese: "鼻子", pinyin: "bízi", english: "nose", hsk: 2, category: "body" },
  { id: 300, chinese: "嘴", pinyin: "zuǐ", english: "mouth", hsk: 2, category: "body" },
  { id: 301, chinese: "耳朵", pinyin: "ěrduo", english: "ear", hsk: 2, category: "body" },
  { id: 302, chinese: "手", pinyin: "shǒu", english: "hand", hsk: 2, category: "body" },
  { id: 303, chinese: "脚", pinyin: "jiǎo", english: "foot", hsk: 2, category: "body" },
  { id: 304, chinese: "肚子", pinyin: "dùzi", english: "stomach / belly", hsk: 2, category: "body" },
];
